const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

/**
 * PropFi India — Deployment Script (All-India Scale)
 *
 * - Deploys MockUSDC + PropFiMaster
 * - Lists ALL properties via batchListProperties() (50 per tx)
 * - Reads from export/property_data.json (generated by generate_properties.js)
 * - Writes export/deployed_addresses.json and export/constants.js
 */

const BATCH_SIZE = 50; // Max per batchListProperties() call
const DEMO_SEED_COUNT = 5; // Buy tokens on first N properties for demo

async function main() {
  const [deployer] = await ethers.getSigners();
  const network = await ethers.provider.getNetwork();
  const isLocalNetwork = network.chainId === 31337n;

  console.log("\n🚀 PropFi India — ALL-INDIA Deployment");
  console.log("📡 Network:", network.name, `(chainId: ${network.chainId})`);
  console.log("📍 Deployer:", deployer.address);
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("💰 Balance:", ethers.formatEther(balance), "MATIC\n");

  // ============================================================
  // STEP 1: Deploy MockUSDC
  // ============================================================
  console.log("📄 [1/4] Deploying MockUSDC...");
  const MockUSDC = await ethers.getContractFactory("MockUSDC");
  const mockUSDC = await MockUSDC.deploy();
  await mockUSDC.waitForDeployment();
  const usdcAddress = await mockUSDC.getAddress();
  console.log("    ✅ MockUSDC:", usdcAddress);

  // ============================================================
  // STEP 2: Deploy PropFiMaster
  // ============================================================
  console.log("\n📄 [2/4] Deploying PropFiMaster...");
  const PropFiMaster = await ethers.getContractFactory("PropFiMaster");
  const propFiMaster = await PropFiMaster.deploy(usdcAddress);
  await propFiMaster.waitForDeployment();
  const propFiAddress = await propFiMaster.getAddress();
  console.log("    ✅ PropFiMaster:", propFiAddress);

  // ============================================================
  // STEP 3: Batch list all properties
  // ============================================================
  console.log("\n🏠 [3/4] Listing ALL-INDIA properties in batches of", BATCH_SIZE, "...");

  const propertyDataPath = path.join(__dirname, "../export/property_data.json");
  const { properties, stats } = JSON.parse(fs.readFileSync(propertyDataPath, "utf8"));

  console.log(`    📊 Total: ${properties.length} properties across ${stats.statesAndUTs} states/UTs, ${stats.cities || stats.statesAndUTs} locations`);

  let listedCount = 0;
  let batchNumber = 0;
  const listedIds = [];

  // Chunk into batches of BATCH_SIZE
  for (let i = 0; i < properties.length; i += BATCH_SIZE) {
    const batch = properties.slice(i, i + BATCH_SIZE);
    batchNumber++;

    const inputs = batch.map((prop) => ({
      name: prop.name,
      area: prop.area || prop.city,
      city: prop.city,
      state: prop.state,
      propertyType: prop.propertyType,
      pricePerToken: ethers.parseUnits(Math.max(1, prop.pricePerToken).toString(), 6),
      totalTokens: prop.totalTokens,
    }));

    // On testnet, add delay between batches to avoid nonce issues
    if (!isLocalNetwork && batchNumber > 1) {
      await sleep(2000);
    }

    const tx = await propFiMaster.batchListProperties(inputs);
    const receipt = await tx.wait();

    listedCount += batch.length;
    listedIds.push(...batch.map((p) => ({ id: p.id, name: p.name, city: p.city, state: p.state })));

    // Progress reporting every 5 batches
    if (batchNumber % 5 === 0 || i + BATCH_SIZE >= properties.length) {
      const pct = Math.round((listedCount / properties.length) * 100);
      console.log(`    📦 Batch ${batchNumber} done | ${listedCount}/${properties.length} properties (${pct}%)`);
    }
  }

  console.log(`\n    ✅ Listed ${listedCount} properties across ALL of India!`);

  // ============================================================
  // STEP 4: Seed demo state
  // ============================================================
  console.log("\n🌱 [4/4] Seeding demo state...");

  // Mint 10M USDC in 10 separate calls (1M max per call)
  for (let i = 0; i < 10; i++) {
    await (await mockUSDC.mint(deployer.address, ethers.parseUnits("1000000", 6))).wait();
  }
  console.log("    ✅ Minted 10,000,000 mUSDC to deployer");

  const propFiAddr = await propFiMaster.getAddress();
  await (await mockUSDC.approve(propFiAddr, ethers.parseUnits("10000000", 6))).wait();

  for (let i = 1; i <= Math.min(DEMO_SEED_COUNT, properties.length); i++) {
    await (await propFiMaster.buyFractionalToken(i, 100)).wait();
    console.log(`    ✅ Demo: Bought 100 tokens for Property ID ${i} (${properties[i - 1].name}, ${properties[i - 1].state})`);
  }

  // ============================================================
  // WRITE OUTPUT FILES
  // ============================================================
  const exportDir = path.join(__dirname, "../export");
  if (!fs.existsSync(exportDir)) fs.mkdirSync(exportDir, { recursive: true });

  // deployed_addresses.json
  const deployedData = {
    network: network.name,
    chainId: Number(network.chainId),
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
    contracts: { MockUSDC: usdcAddress, PropFiMaster: propFiAddress },
    totalProperties: listedCount,
    statesAndUTs: stats.statesAndUTs,
    sampleProperties: listedIds.slice(0, 20),
  };
  fs.writeFileSync(
    path.join(exportDir, "deployed_addresses.json"),
    JSON.stringify(deployedData, null, 2)
  );

  // constants.js (auto-generated for Frontend team)
  const usdcArtifact = JSON.parse(fs.readFileSync(
    path.join(__dirname, "../artifacts/contracts/MockUSDC.sol/MockUSDC.json"), "utf8"
  ));
  const propFiArtifact = JSON.parse(fs.readFileSync(
    path.join(__dirname, "../artifacts/contracts/PropFiMaster.sol/PropFiMaster.json"), "utf8"
  ));

  const constantsContent = `// ============================================================
// PropFi India — Web3 Constants (AUTO-GENERATED)
// ${properties.length} Properties | ${stats.statesAndUTs} States/UTs
// Network: ${network.name} | chainId: ${Number(network.chainId)}
// Deployed: ${new Date().toISOString()}
// ============================================================

export const USDC_ADDRESS = "${usdcAddress}";
export const PROPFI_MASTER_ADDRESS = "${propFiAddress}";
export const CHAIN_ID = ${Number(network.chainId)};
export const NETWORK_NAME = "${network.name}";
export const RPC_URL = "https://rpc-amoy.polygon.technology";
export const BLOCK_EXPLORER = "https://amoy.polygonscan.com";
export const TOTAL_PROPERTIES = ${listedCount};

export const USDC_ABI = ${JSON.stringify(usdcArtifact.abi, null, 2)};

export const PROPFI_MASTER_ABI = ${JSON.stringify(propFiArtifact.abi, null, 2)};
`;

  fs.writeFileSync(path.join(exportDir, "constants.js"), constantsContent);

  // ============================================================
  // FINAL SUMMARY
  // ============================================================
  console.log("\n" + "=".repeat(65));
  console.log("🎉 DEPLOYMENT COMPLETE — PropFi India (All-India)");
  console.log("=".repeat(65));
  console.log(`📍 MockUSDC:          ${usdcAddress}`);
  console.log(`📍 PropFiMaster:      ${propFiAddress}`);
  console.log(`🏠 Properties Listed: ${listedCount}`);
  console.log(`🗺️  States/UTs:        ${stats.statesAndUTs}`);
  console.log(`🏙️  Cities/Towns:      ${stats.cities || "Multiple"}`);
  console.log(`📁 Files: export/deployed_addresses.json`);
  console.log(`📁 Files: export/constants.js (share with Frontend Team)`);
  console.log("=".repeat(65));

  if (!isLocalNetwork) {
    console.log("\n🔗 Verify on Polygonscan:");
    console.log(`   MockUSDC:     https://amoy.polygonscan.com/address/${usdcAddress}`);
    console.log(`   PropFiMaster: https://amoy.polygonscan.com/address/${propFiAddress}`);
  }
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Deployment failed:", error);
    process.exit(1);
  });
